/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.casopractivo_primerparcial;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Random;

/**
 *
 * @author kenph
 */
public class Ventana extends javax.swing.JFrame {

    /**
     * Creates new form Ventana
     */
    public Ventana() {
        initComponents();
    }

    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        IngresarNombresEmpresas = new javax.swing.JButton();
        GenerarIngresos = new javax.swing.JButton();
        CalcularIngresoMayor = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaIngresosTextArea = new javax.swing.JTextArea();
        CalcularIngresoMenor = new javax.swing.JButton();
        desplegarCamaraIndustria = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("Industrias Empresariales ");

        IngresarNombresEmpresas.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        IngresarNombresEmpresas.setText("Ingresar Empresas");
        IngresarNombresEmpresas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IngresarNombresEmpresasActionPerformed(evt);
            }
        });

        GenerarIngresos.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        GenerarIngresos.setText("Generar Ingresos");
        GenerarIngresos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GenerarIngresosActionPerformed(evt);
            }
        });

        CalcularIngresoMayor.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        CalcularIngresoMayor.setText("Calcular Mayor Ingreso");
        CalcularIngresoMayor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalcularIngresoMayorActionPerformed(evt);
            }
        });

        tablaIngresosTextArea.setColumns(20);
        tablaIngresosTextArea.setRows(5);
        jScrollPane1.setViewportView(tablaIngresosTextArea);

        CalcularIngresoMenor.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        CalcularIngresoMenor.setText("Calcular Menor Ingreso");
        CalcularIngresoMenor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalcularIngresoMenorActionPerformed(evt);
            }
        });

        desplegarCamaraIndustria.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        desplegarCamaraIndustria.setText("Desplegar Tabla Industria");
        desplegarCamaraIndustria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                desplegarCamaraIndustriaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(CalcularIngresoMayor)
                                    .addComponent(IngresarNombresEmpresas)
                                    .addComponent(CalcularIngresoMenor))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(GenerarIngresos)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(28, 28, 28)
                .addComponent(desplegarCamaraIndustria)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 464, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addComponent(IngresarNombresEmpresas)
                                .addGap(18, 18, 18)
                                .addComponent(GenerarIngresos)
                                .addGap(30, 30, 30)
                                .addComponent(CalcularIngresoMayor)
                                .addGap(31, 31, 31)
                                .addComponent(CalcularIngresoMenor))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(72, 72, 72)
                                .addComponent(desplegarCamaraIndustria)))
                        .addGap(51, 51, 51))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
//Matrices y vectores para el programa
    int[][] ingresos; 
    String[] nombresEmpresas;
    int Años = 4;
    
    private void IngresarNombresEmpresasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IngresarNombresEmpresasActionPerformed
        nombresEmpresas = new String[5]; //Vector donde se almacenara el nombre de las empresas
        for (int i = 0; i < 5; i++) { //Recorrera desde 0 hasta cuatro (5 empresas)
            nombresEmpresas[i] = JOptionPane.showInputDialog("Ingresar el nombre de cada empresa: " + (i + 1) + ":"); //Aqui aparecera la ventana para ingresar el nombre de cada empresa
        }
    }//GEN-LAST:event_IngresarNombresEmpresasActionPerformed

    private void GenerarIngresosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GenerarIngresosActionPerformed
        ingresos = new int[nombresEmpresas.length][4];
        Random random = new Random();   //funcion que va a generar numeros aleatorios

        for (int i = 0; i < nombresEmpresas.length; i++) {
            for (int j = 0; j < 4; j++) {
                ingresos[i][j] = random.nextInt(100000 + 1); // Número máximo de ingresos0 100,000
            }
        }
    }//GEN-LAST:event_GenerarIngresosActionPerformed

    private void CalcularIngresoMayorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalcularIngresoMayorActionPerformed
        int totalIngresos[] = new int[nombresEmpresas.length]; //nuevo vector TotalIngresos
        for (int i = 0; i < nombresEmpresas.length; i++) {  //Recorre desde cero hasta la longitud de "elementos" en el vector (5 empresas)
            for (int j = 0; j < 4; j++) {
                totalIngresos[i] += ingresos[i][j]; 
            }
        }

        int ingresoMayorTotal = 0;
        for (int i = 1; i < nombresEmpresas.length; i++) {
            if (totalIngresos[i] > totalIngresos[ingresoMayorTotal]) {
                ingresoMayorTotal = i;
            }
        }

        JOptionPane.showMessageDialog(this, "La empresa con el mayor monto de Ingresos es: " + nombresEmpresas[ingresoMayorTotal]);
    }//GEN-LAST:event_CalcularIngresoMayorActionPerformed

    private void CalcularIngresoMenorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalcularIngresoMenorActionPerformed
        
        int menorIngreso = 0;
        
        int totalIngresosMenor = Integer.MAX_VALUE; //Valor maximo
        
        //funcion para encontrar el ingreso mas bajo
        for (int i = 0; i < nombresEmpresas.length; i++) {
            int totalIngresos = 0;
            for (int j = 0; j < 4; j++) {
                totalIngresos += ingresos[i][j];
            }
            if (totalIngresos < totalIngresosMenor) {
                menorIngreso = i;
                totalIngresosMenor = totalIngresos;
        }

        JOptionPane.showMessageDialog(this, "La empresa con el ingreso mas bajo es: " + nombresEmpresas[menorIngreso]);
    }//GEN-LAST:event_CalcularIngresoMenorActionPerformed

    private void desplegarCamaraIndustriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_desplegarCamaraIndustriaActionPerformed
        // TODO add your handling code here:
        StringBuilder tablaIngresos = new StringBuilder("Camara de Industria (2015-2017):\n\n");
        for (int i = 0; i < nombresEmpresas.length; i++) {
            tablaIngresos.append(nombresEmpresas[i]).append(": ");
            for (int j = 0; j < 4; j++) {
                tablaIngresos.append(ingresos[i][j]).append(" ");
            }
            tablaIngresos.append("\n");
        }
        tablaIngresosTextArea.setText(tablaIngresos.toString());
    }//GEN-LAST:event_desplegarCamaraIndustriaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CalcularIngresoMayor;
    private javax.swing.JButton CalcularIngresoMenor;
    private javax.swing.JButton GenerarIngresos;
    private javax.swing.JButton IngresarNombresEmpresas;
    private javax.swing.JButton desplegarCamaraIndustria;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea tablaIngresosTextArea;
    // End of variables declaration//GEN-END:variables
}
